import unicodedata


COUNTRY_TO_LANGUAGE = {
    "ad": "fr",
    "ae": "ar",
    "af": "fa",
    "ag": "en",
    "ai": "en",
    "an": "nl",
    "ao": "pt",
    "ar": "es",
    "as": "en",
    "at": "de",
    "au": "en",
    "aw": "nl",
    "ax": "sv",
    "ba": "hr",
    "bb": "en",
    "bd": "bn",
    "be": "nl",
    "bf": "fr",
    "bg": "bg",
    "bh": "ar",
    "bi": "fr",
    "bj": "fr",
    "bm": "en",
    "bn": "ms",
    "bo": "es",
    "br": "pt",
    "bs": "en",
    "bw": "en",
    "bz": "en",
    "ca": "en",
    "cc": "ms",
    "cd": "fr",
    "cf": "fr",
    "cg": "fr",
    "ch": "de",
    "ci": "fr",
    "ck": "en",
    "cl": "es",
    "cm": "fr",
    "cn": "zh",
    "co": "es",
    "cr": "es",
    "cs": "sr",
    "cu": "es",
    "cv": "pt",
    "cx": "ms",
    "cy": "el",
    "cz": "cs",
    "de": "de",
    "dj": "fr",
    "dk": "da",
    "dm": "en",
    "do": "es",
    "dz": "ar",
    "ec": "es",
    "ee": "et",
    "eg": "ar",
    "er": "en",
    "es": "es",
    "et": "en",
    "fi": "fi",
    "fj": "en",
    "fk": "en",
    "fm": "en",
    "fo": "da",
    "fr": "fr",
    "ga": "fr",
    "gb": "en",
    "gd": "en",
    "gf": "fr",
    "gh": "en",
    "gi": "en",
    "gl": "da",
    "gm": "en",
    "gn": "fr",
    "gp": "fr",
    "gq": "es",
    "gr": "el",
    "gt": "es",
    "gu": "en",
    "gw": "pt",
    "gy": "en",
    "hk": "zh",
    "hn": "es",
    "hr": "hr",
    "ht": "fr",
    "hu": "hu",
    "id": "id",
    "ie": "en",
    "il": "he",
    "in": "hi",
    "io": "en",
    "iq": "ar",
    "ir": "fa",
    "it": "it",
    "jm": "en",
    "jo": "ar",
    "jp": "ja",
    "ke": "en",
    "ki": "en",
    "km": "fr",
    "kn": "en",
    "kp": "ko",
    "kr": "ko",
    "kw": "ar",
    "ky": "en",
    "lb": "ar",
    "lc": "en",
    "li": "de",
    "lr": "en",
    "ls": "en",
    "lt": "lt",
    "lu": "fr",
    "lv": "lv",
    "ly": "ar",
    "ma": "ar",
    "mc": "fr",
    "md": "ro",
    "mg": "fr",
    "mh": "en",
    "ml": "fr",
    "mo": "zh",
    "mp": "en",
    "mq": "fr",
    "mr": "ar",
    "ms": "en",
    "mt": "en",
    "mu": "en",
    "mw": "en",
    "mx": "es",
    "my": "ms",
    "mz": "pt",
    "na": "en",
    "nc": "fr",
    "ne": "fr",
    "nf": "en",
    "ng": "en",
    "ni": "es",
    "nl": "nl",
    "no": "no",
    "nr": "en",
    "nu": "en",
    "nz": "en",
    "om": "ar",
    "pa": "es",
    "pe": "es",
    "pf": "fr",
    "pg": "en",
    "ph": "en",
    "pk": "en",
    "pl": "pl",
    "pm": "fr",
    "pn": "en",
    "pr": "es",
    "ps": "ar",
    "pt": "pt",
    "pw": "en",
    "py": "es",
    "qa": "ar",
    "re": "fr",
    "ro": "ro",
    "ru": "ru",
    "rw": "fr",
    "sa": "ar",
    "sb": "en",
    "sc": "en",
    "sd": "ar",
    "se": "sv",
    "sg": "en",
    "sh": "en",
    "si": "hu",
    "sk": "sk",
    "sl": "en",
    "sm": "it",
    "so": "ar",
    "sr": "nl",
    "st": "pt",
    "sv": "es",
    "sy": "ar",
    "sz": "en",
    "tc": "en",
    "td": "fr",
    "tg": "fr",
    "th": "th",
    "tk": "en",
    "tl": "pt",
    "tn": "ar",
    "to": "en",
    "tr": "tr",
    "tt": "en",
    "tw": "zh",
    "ua": "uk",
    "ug": "en",
    "um": "en",
    "us": "en",
    "uy": "es",
    "va": "it",
    "vc": "en",
    "ve": "es",
    "vg": "en",
    "vi": "en",
    "vn": "vi",
    "vu": "en",
    "wf": "fr",
    "ws": "en",
    "ye": "ar",
    "yt": "fr",
    "yu": "sr",
    "za": "en",
    "zm": "en",
    "zw": "en",
}


def alias_language(scope: str) -> str | None:
    if scope.startswith("lang:"):
        language = scope[5:]
        if len(language) == 2 and language.isascii() and language.isalpha():
            return language
        return None
    return COUNTRY_TO_LANGUAGE.get(scope)


def select_indexer_titles(
    title: str,
    aliases: object,
    languages: list[str],
) -> tuple[str, ...]:
    """Return ordered, unique search titles for the configured languages."""

    selected = []
    seen = set()

    def append(candidate: object):
        if not isinstance(candidate, str) or not (
            candidate := " ".join(candidate.split())
        ):
            return
        identity = unicodedata.normalize("NFKC", candidate).casefold()
        if identity in seen:
            return
        seen.add(identity)
        selected.append(candidate)

    append(title)
    if not languages or not isinstance(aliases, dict):
        return tuple(selected)

    aliases_by_language: dict[str, list[str]] = {}
    for country, country_titles in aliases.items():
        if not isinstance(country, str) or not isinstance(country_titles, list):
            continue
        language = alias_language(country.lower())
        if language is not None:
            aliases_by_language.setdefault(language, []).extend(country_titles)

    for language in languages:
        for alias in aliases_by_language.get(language, ()):
            append(alias)

    return tuple(selected)
